Add back working extract report
egraphs-good/egglog pull request #205
Opened 2023-08-23 17:13 UTC by saulshanabrook

In the switch to using an extract action over an extract command in #176, the saving of the extracted expressions in a report was lost.

This PR restores that behavior and also refactors the `ExtractReport` to be an enum. In #176, the extraction logic was also changed, so that if passed in a non-zero number of variants, it would no longer perform a normal cost based extraction as well. So now the report captures these two cases as distinct.

2023-08-23 17:14 UTC, saulshanabrook commented on src/lib.rs
> -    pub fn extract_expr(&mut self, e: Expr, num_variants: usize) -> Result<ExtractReport, Error> {
This function was previously used in a number of places before #176 and was now only being used in the un-tested Output command.

2023-08-23 17:18 UTC, mwillsey commented
Do we want the report to be an enum? I feel that the single and multiple extraction case could be handled uniformly, no?

2023-08-23 17:29 UTC, saulshanabrook commented
> Do we want the report to be an enum? I feel that the single and multiple extraction case could be handled uniformly, no?

The logic now for the extraction now seems disjoint between the variants in the best. If there are varients, then there is no "best" expression extracted, and vice versa:

https://github.com/egraphs-good/egglog/blob/9e530381961a59524f2bbacd89973575b4e036d8/src/typecheck.rs#L879-L909

Whereas previously, if you extracted some variants, a best was also extracted.

So I thought now an enum is appropriate?

2023-08-23 17:42 UTC, saulshanabrook commented
On another note, I noticed that `simplify` is not working with this new scheme, due to it running the extraction in a sub-egraph.

As a solution, I am considering changing from a saved "report" to a callback on the EGraph which is called during extraction.

Any thoughts on that?

2023-08-23 18:00 UTC, mwillsey commented
What simplify are we talking about? I’m not sure what the callback would do.

On Wed, Aug 23, 2023 at 10:42 AM Saul Shanabrook ***@***.***>
wrote:

> On another note, I noticed that simplify is not working with this new
> scheme, due to it running the extraction in a sub-egraph.
>
> As a solution, I am considering changing from a saved "report" to a
> callback on the EGraph which is called during extraction.
>
> Any thoughts on that?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/egraphs-good/egglog/pull/205#issuecomment-1690376150>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANTPTDSK7IR6UMXREKY44LXWY6IFANCNFSM6AAAAAA33ZJDC4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-08-23 18:10 UTC, saulshanabrook commented
> What simplify are we talking about?


The `simplify` command, i.e. like for this example:

```
(datatype Expr
  (Num i64))

(let x (Num 1))
(simplify (run) x)
```

> I’m not sure what the callback would do.

Instead of adding a report, it would call a callback on every extraction, so that from Python, we could still see what was extracted.

I opted not to do this, due to the added complexity, and instead copy reports from children to parents when popping.

2023-08-23 18:22 UTC, oflatt approved these changes
looks like a good change to me!

2023-08-29 18:53 UTC, oflatt requested changes
This looks like a good change, and fixes a bug in preserving messages across push/pop.
Had a small nit before we merge.

2023-08-29 18:53 UTC, oflatt commented on src/lib.rs
> +                    self.extract_report = Some(report);
Use `Option.or` instead of this if statement

2023-08-29 20:39 UTC, oflatt approved these changes

2023-08-29 20:39 UTC, merged