Fix `query-extract` for `vec`
egraphs-good/egglog pull request #242
Opened 2023-10-01 09:51 UTC by hatoo

Currently, `query-extract` for `vec` prints the reverse order of the argument

```
(sort IVec (Vec i64))

(let e (vec-of 1 2 3 4))
(query-extract e) ; => (vec-push (vec-push (vec-push (vec-push (vec-empty) 4) 3) 2) 1)

(check (= e (vec-push (vec-push (vec-push (vec-push (vec-empty) 4) 3) 2) 1))) ; fail
```

This PR fixes it and prints by `vec-of`

```
(sort IVec (Vec i64))

(let e (vec-of 1 2 3 4))
(query-extract e) ; => (vec-of 1 2 3 4)
(query-extract (vec-empty)) ; => (vec-empty)

(check (= e (vec-of 1 2 3 4))) ; OK
```

2023-10-02 16:37 UTC, oflatt approved these changes
Good catch!

2023-10-02 16:38 UTC, oflatt requested changes
Great catch, could you please also add a repro test for this?

2023-10-03 02:00 UTC, hatoo commented
Added.
I'm not sure it's the best way to test this though.

2023-10-04 19:58 UTC, oflatt approved these changes
Thanks!

2023-10-04 19:59 UTC, merged