Display build info when running egglog
egraphs-good/egglog pull request #427
Opened 2024-09-25 22:17 UTC by yihozhang

This is useful when you install egglog to the system via `cargo install --path .` and later want to find out what the exact version you installed is.

After this PR:
```
> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/egglog`
[INFO ] Welcome to Egglog! (build: 0.2.0_2024-09-25_5bf9dee)
```

and

```
> cargo run -- --version
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/egglog --version`
egglog 0.2.0_2024-09-25_5bf9dee
```

2024-09-25 22:19 UTC, yihozhang commented on Cargo.toml
> +chrono = { version = "0.4", default-features = false, features = ["now"] }
I disabled the default feature set because it will otherwise import a complex set of dependencies due to the `locale` feature.

2024-09-26 16:20 UTC, ezrosent requested changes

2024-09-26 16:20 UTC, ezrosent commented on build.rs
> +    let output = Command::new("git")
Can we make this optional info? (along with the `CARGO_PKG_VERSION` query).

That way we can still run / build this on machines that don't have git, or similar.

2024-09-26 21:32 UTC, yihozhang commented
@ezrosent Thanks, I've made the dependency on git optional:

With this PR, if we change `git` in the command to a non-existent command:
```
> cargo run
   Compiling egglog v0.2.0 (/Users/yihongzhang/egglog)
    Finished dev [unoptimized + debuginfo] target(s) in 2.77s
     Running `target/debug/egglog`
[INFO ] Welcome to Egglog! (build: 0.2.0_2024-09-26)
```

2024-09-27 04:11 UTC, ezrosent approved these changes

2024-09-28 04:22 UTC, merged